# Option 1

In [1]:
! uv pip install pyarrow

Using Python 3.12.7 environment at: /home/mgill/code/cz-benchmarks/.venv
Audited 1 package in 3ms

In [2]:
# %load_ext autoreload
# %autoreload 2

In [3]:
from pathlib import Path
import scanpy as sc
import numpy as np
import json
import pandas as pd
from tqdm import tqdm
import os

## Load Authors H5AD Data

In [4]:
replogle_dir = Path('/data2/czbenchmarks/replogle2022')
! ls {replogle_dir}

．
deg_jg
K562
k562_ctrl_for_batch_integration.h5ad
K562_essential_normalized_singlecell_01.h5ad
K562_essential_raw_singlecell_01.h5ad
K562_gwps_normalized_singlecell_01.h5ad
K562_gwps_raw_singlecell_01.h5ad
raw_cr4
raw_filt_h5ad
raw_h5ad_from_cr4
README.md

In [5]:
adata = sc.read_h5ad(f"{replogle_dir}/K562_essential_raw_singlecell_01.h5ad")
adata.obs = adata.obs.rename(columns={'gene_id':'condition', 'gene':'condition_name'})
adata.var = adata.var.rename(columns={'gene_name':'gene'})
print(adata.shape)

(310385, 8563)

In [6]:
adata.obs.head(n=2).T

cell_barcode,AAACCCAAGAAATCCA-27,AAACCCAAGAACTTCC-31
gem_group,27,31
condition_name,NAF1,BUB1
condition,ENSG00000145414,ENSG00000169679
transcript,P1P2,P1P2
gene_transcript,5449_NAF1_P1P2_ENSG00000145414,935_BUB1_P1P2_ENSG00000169679
sgID_AB,NAF1_+_164087918.23-P1P2|NAF1_-_164087674.23-P1P2,BUB1_-_111435363.23-P1P2|BUB1_-_111435372.23-P1P2
mitopercent,0.112083,0.179895
UMI_count,11438.0,5342.0
z_gemgroup_UMI,0.013047,-1.522247
core_scale_factor,0.813253,0.844107
core_adjusted_UMI_count,14064.512695,6328.584473

In [7]:
adata.var.head(n=2)

,gene,chr,start,end,class,strand,length,in_matrix,mean,std,cv,fano
gene_id,,,,,,,,,,,,
ENSG00000237491,LINC01409,chr1,778747,810065,gene_version10,+,31318,True,0.137594,0.380048,2.762105,1.049733
ENSG00000228794,LINC01128,chr1,825138,868202,gene_version9,+,43064,True,0.256720,0.520162,2.026184,1.053944

## Gene Name to Ensembl ID Mapper
This will be used to map the condition from gene name to ensembl_id in the auxilary data.

In [8]:
map_gene_name_to_ensembl_id_pkl = 'map_gene_name_to_ensembl_id.pkl'

obs_mapper = adata.obs[['condition_name', 'condition']].drop_duplicates().set_index('condition_name').rename(columns={'condition':'ensembl_id'})
assert obs_mapper.shape[0] == obs_mapper['ensembl_id'].nunique() == obs_mapper.index.nunique()

# var_mapper = adata.var[['gene_name']].reset_index().rename(columns={'gene_name':'gene', 'gene_id':'ensembl_id'}).set_index('gene')
# assert var_mapper.shape[0] == var_mapper['ensembl_id'].nunique() == var_mapper.index.nunique()

map_gene_name_to_ensembl_id = obs_mapper # var_mapper is not fully unique
# map_gene_name_to_ensembl_id.to_pickle(map_gene_name_to_ensembl_id_pkl)

In [9]:
map_gene_name_to_ensembl_id.head()

                     ensembl_id
condition_name
NAF1            ENSG00000145414
BUB1            ENSG00000169679
UBL5            ENSG00000198258
C9orf16         ENSG00000171159
TIMM9           ENSG00000100575

## Background Matched Controls

In [10]:
# control_cells_path = replogle_dir / "deg_jg/ReplogleEssentialsCr4_GEM_libsizeMatched_NonTargetingCellIdsPerTarget.json"
control_cells_path = "/data2/czbenchmarks/control_cells_ids_replogle_k562_essential_perturbpredict_new.json"

with open(control_cells_path, 'r') as fh:
    control_cells_ids = json.load(fh)

control_cells_ids.pop('non-targeting', None)

In [11]:
keys_ = list(control_cells_ids.keys())
print(keys_[:2], control_cells_ids[keys_[0]])

['ENSG00000145414', 'ENSG00000169679'] {'AAACCCAAGAAATCCA-27': 'GAGGGATTCGTGGACC-27', 'AAACGAAAGTCATCGT-17': 'AGTGCCGGTCATGACT-17', 'AATGCCACAGCTGTAT-47': 'TGCGGCAAGACAACTA-47', 'ACAGAAATCAACTGAC-10': 'AAATGGACAGAGTAAT-10', 'ACATCCCTCTGACGCG-34': 'CAACCTCAGGCACTAG-34', 'ACCTGAATCGGATTAC-13': 'TCACACCGTCCCACGA-13', 'ACGGGTCCAATAAGGT-40': 'GAGACCCTCCTAGAGT-40', 'ACTATCTAGCGGCTCT-22': 'GTTGAACCAACAACAA-22', 'ACTCTCGGTATGTGTC-37': 'AGACACTAGCATTGAA-37', 'AGAACCTGTTCGAAGG-9': 'TCCTCGAGTATTCCGA-9', 'AGAGAGCTCCAGTGCG-13': 'CGTGTCTAGAGTTCGG-13', 'AGATGAAGTCCCGGTA-13': 'CTGTAGACATCCTAAG-13', 'AGCATCAAGACTAGAT-23': 'AATGAAGAGTTGCTCA-23', 'AGCGATTTCACTCCGT-31': 'CCTTGTGGTCTTGAGT-31', 'AGCTCAACAGGAAGTC-2': 'GATCATGGTCTTCCGT-2', 'AGGAATAAGCGCTTCG-47': 'AACGGGAAGAACCGCA-47', 'AGGTGTTAGAGGACTC-3': 'CTGGACGAGTCATGAA-3', 'ATCCGTCAGTTCCATG-28': 'CATTCATCACCTGCAG-28', 'ATCCTATCACAAGTGG-43': 'CGGCAGTAGTATTGCC-43', 'ATCGTGACACCGCTAG-16': 'AAGCCATTCAACTCTT-16', 'ATTACCTAGACTTGTC-32': 'TCCTTTCTCTACCAGA-32', 'ATTGGGTCAATTTCTC-30': 'GAAGTAATCGAACTCA-30', 'CAAAGAAGTACAGCGA-11': 'AGAAATGAGACTACCT-11', 'CAACCTCTCCTACCAC-45': 'GCATGATTCACGATCA-45', 'CACCAAAAGCAATTAG-39': 'TTACAGGTCCATTGTT-39', 'CACCGTTAGGGCGAGA-37': 'TTCGGTCAGTTTGCTG-37', 'CACGTTCAGTTACGGG-22': 'TATATCCAGGTGAGCT-22', 'CAGAGCCTCACATACG-13': 'TGCTCGTAGTAGCTCT-13', 'CAGCGTGTCGTTTACT-48': 'AGACCATGTTCGTACA-48', 'CAGTGCGCATTGGGAG-19': 'AAGCGTTAGAGTTCGG-19', 'CATCCACAGACGTCGA-29': 'CGTTCTGCAACCACAT-29', 'CCATAAGAGCCGGATA-27': 'TTCTTGAGTTATCCAG-27', 'CCCAACTAGCATCGAG-24': 'TGAGGAGCAGCGACCT-24', 'CCTCAACCACGCTGTG-26': 'ACTTTCATCGAACTCA-26', 'CGCCAGAGTGGGAGAG-19': 'GAGTGTTCAGGGTTGA-19', 'CGGCAGTGTAGTTAGA-24': 'GCTCAAATCCAGTACA-24', 'CGGGTGTCATTAAGCC-4': 'TCCTCTTGTACACGCC-4', 'CGTGAATGTACGCGTC-29': 'GATCATGGTTTACGTG-29', 'CGTTGGGGTATCTCTT-29': 'CACATGAAGCCTCAGC-29', 'CTACCCATCGACGATT-14': 'GGAGAACCAAGCAATA-14', 'CTCCAACGTGCCTTTC-22': 'GTTATGGGTAACAGGC-22', 'CTGAGCGGTCGTGCCA-7': 'AACCTGACACAACCGC-7', 'CTGAGGCCATCTAACG-15': 'GGGACCTGTGATACCT-15', 'CTGCAGGGTTTCTTAC-2': 'TCCTTCTGTGAGCAGT-2', 'CTTGAGACAAGGCCTC-8': 'GTTGAACGTTCGATTG-8', 'GAAGCCCGTTCTCCAC-33': 'TCGCTCATCGTTAGTG-33', 'GAATAGAGTGAAGCGT-37': 'ACAGCCGAGCTAAATG-37', 'GACCCTTGTGGATACG-18': 'GTACAGTCATCCCACT-18', 'GACGCTGAGATAGCTA-19': 'GCAGTTAGTCTAGATC-19', 'GATCATGCAGTCGAGA-33': 'AACCACAGTGCCGGTT-33', 'GATGATCCAGGAATCG-9': 'CCCTTAGGTCGTATGT-9', 'GCAACATAGAGTGTGC-10': 'ACTATGGGTTACACAC-10', 'GCATCGGTCGGTGTTA-40': 'CGTTAGAAGACATAAC-40', 'GCATGATTCACTTGGA-45': 'CAATCGATCGACATAC-45', 'GCATTAGCACCGTCTT-16': 'ATCAGGTTCCATGATG-16', 'GCCGATGGTTACGTAC-1': 'GAAGAATGTATGAAGT-1', 'GCCGTGATCATGAGGG-18': 'AGAAGCGTCGCCCAGA-18', 'GCGTGCAGTTTGTTCT-19': 'TTAGGGTGTCAAGTTC-19', 'GCTTTCGGTGTGTGGA-18': 'AACCCAAGTAGCGATG-18', 'GGATGTTCAATTCACG-34': 'AGACCCGCATGGGAAC-34', 'GGGATGATCGGCTTCT-22': 'TTCCTTCCACCTCGTT-22', 'GTCATGACAAACACGG-6': 'GTGGCGTCAAGATTGA-6', 'GTCGTAATCCAAGCCG-22': 'CTGTCGTCAAATGATG-22', 'GTGATGTAGCTGTGCC-46': 'ACTGCAAGTCACAATC-46', 'GTGGGAACAGAAACCG-29': 'TGAGGAGCACACGGTC-29', 'GTGTAACTCGCTTGAA-3': 'TTTCGATAGGCACCAA-3', 'TAGACTGAGCAATTCC-45': 'ATCACGAAGAGGACTC-45', 'TAGGGTTCACCTCTGT-35': 'CTTCGGTCACTACTTT-35', 'TAGGTACTCGTTGTGA-43': 'AATAGAGAGATGTAGT-43', 'TATTGGGCACATATCG-9': 'CTCAGAAGTAAGATCA-9', 'TCAAGCATCATTGAGC-33': 'CTGGTCTGTGTGATGG-33', 'TCACGCTAGAGAGTTT-17': 'AGGACGATCCTCGCAT-17', 'TCATACTAGGGTCACA-5': 'GTTGAACCAAACGGCA-5', 'TCCCACAAGACGCTCC-24': 'GTGATGTTCCCGTGAG-24', 'TCCCATGGTATCGATC-33': 'TTGAACGCAATTCTCT-33', 'TCCGGGAAGAGGATGA-10': 'TTCGATTGTCGTGCCA-10', 'TCCTCTTTCGACCATA-7': 'CTTGATTGTGATAGAT-7', 'TCGCTTGAGGGCAAGG-29': 'TAGAGTCTCGATGCAT-29', 'TCTACATTCGCCGAAC-27': 'GGCTTTCGTTAACAGA-27', 'TCTGTCGTCCAATCTT-38': 'GTTGCGGAGACTCAAA-38', 'TGAATCGGTCAACATC-2': 'TACTTGTAGCTGTGCC-2', 'TGAATCGTCCATAAGC-1': 'GTCTGTCGTCATCTAG-1', 'TGAGGAGGTCCCGGTA-35': 'TGTAACGGTAATTAGG-35', 'TGCGATACACCACATA-40': 'AGACCCGTCTTCGCTG-40', 'TGCTTGCCAAATACGA-39': 'GGTAGAGGTCTCCCTA-39', 'TGGTACAAGGGCTGAT-24': 'TGTTGGACATTCACAG-24', 'TGGTTAGGTGGTTTGT-18': 'TCAGTTTGTTCTCCCA-18', 'TGTCAGAAGTTCATCG-26': 'CCGTGAGTCAAGCTGT-26', 'TTACGCCAGGGCAATC-27': 'GACTATGGTTGTATGC-27', 'TTATTGCCATTGACCA-2': 'TCACACCTCGGCTATA-2', 'TTCCAATAGCTGGTGA-37': 'TATTGCTTCATCACCC-37', 'TTGCATTAGTGGTGAC-29': 'CTGCTCAGTGATACCT-29', 'TTGCGTCAGATCCCAT-5': 'CTCAGAAGTTTACGTG-5', 'TTGGGATTCTGCGTCT-19': 'CCTTCAGTCTGCTTTA-19'}

In [12]:
# index_set = set(adata.obs.index.values)

# # Map gene names to ensembl IDs
# skipped_conditions = []
# control_cells_ensembl_ids = {}
# for key in control_cells_ids.keys():
#     ensembl_id = map_gene_name_to_ensembl_id.loc[key].values[0]

#     if len(control_cells_ids[key]) == 0:
#         print(f"No control cells for {key}")
#     else:
#         if not isinstance(control_cells_ids[key], list):
#             assert control_cells_ids[key].ndim == 1
#         elif ensembl_id not in adata.obs.condition.values:
#             skipped_conditions.append(ensembl_id)
#         else:
#             assert all(x in index_set for x in control_cells_ids[key])
#             control_cells_ensembl_ids[ensembl_id] = list(control_cells_ids[key])

# print(f"Skipped {len(skipped_conditions)} conditions: {skipped_conditions}")
# print(list(control_cells_ensembl_ids.keys())[:10])
# # print(list(control_cells_ensembl_ids['ENSG00000094914'])[:10])

## Differential Expression Data

In [15]:
de_data_file = "/data2/czbenchmarks/replogle_k562_essential_perturbpredict_de_results_control_cells_OLD.h5ad"
de_adata = sc.read_h5ad(de_data_file, backed='r')

de_results = {}
for de_type in ['wilcoxon']:
    de_data = pd.DataFrame(de_adata.uns[f'de_results_{de_type}'])
    de_results[de_type] = de_data

del de_adata

In [ ]:
# de_base_path = "/data2/czbenchmarks/compute_de_results_{de_type}_new.arrow"

# de_results = {}
# for de_type in ['wilcoxon']:
#     de_data_path = de_base_path.format(de_type=de_type)
#     de_data = pd.read_parquet(de_data_path)

#     col_has_nulls = de_data.isnull().any()
#     col_has_nulls = col_has_nulls[col_has_nulls].index.values
#     print(f'The following dataframe columns contain nulls: {col_has_nulls}')

#     # No column name mapping required for Wilcoxon

#     orig_size = len(de_data)
#     de_data = pd.merge(de_data, 
#                        map_gene_name_to_ensembl_id.reset_index().set_index('ensembl_id'), 
#                        left_on='condition', 
#                        right_index=True, 
#                        how='left')
#     assert len(de_data) == orig_size
#     assert not de_data['condition'].isnull().any()
    
#     # de_data.index = de_data.index.astype(str)
#     de_results[de_type] = de_data

In [16]:
de_results[de_type].head()

,gene_id,condition_name,score,logfoldchange,pval,pval_adj,condition
0,ENSG00000245910,SLU7,10.678079,1.049750,1.289127e-26,1.435959e-22,ENSG00000164609
1,ENSG00000177410,SLU7,9.709518,1.018977,2.746308e-22,1.529556e-18,ENSG00000164609
2,ENSG00000255717,SLU7,9.608023,1.691616,7.395531e-22,2.745961e-18,ENSG00000164609
3,ENSG00000149806,SLU7,9.155279,0.675583,5.421733e-20,1.207854e-16,ENSG00000164609
4,ENSG00000161970,SLU7,9.070821,0.609069,1.181242e-19,2.192975e-16,ENSG00000164609

In [18]:
adata.obs.head(n=2).T

cell_barcode,AAACCCAAGAAATCCA-27,AAACCCAAGAACTTCC-31
gem_group,27,31
condition_name,NAF1,BUB1
condition,ENSG00000145414,ENSG00000169679
transcript,P1P2,P1P2
gene_transcript,5449_NAF1_P1P2_ENSG00000145414,935_BUB1_P1P2_ENSG00000169679
sgID_AB,NAF1_+_164087918.23-P1P2|NAF1_-_164087674.23-P1P2,BUB1_-_111435363.23-P1P2|BUB1_-_111435372.23-P1P2
mitopercent,0.112083,0.179895
UMI_count,11438.0,5342.0
z_gemgroup_UMI,0.013047,-1.522247
core_scale_factor,0.813253,0.844107
core_adjusted_UMI_count,14064.512695,6328.584473

In [19]:
adata.var.head(n=2).T

gene_id   ENSG00000237491 ENSG00000228794
gene            LINC01409       LINC01128
chr                  chr1            chr1
start              778747          825138
end                810065          868202
class      gene_version10   gene_version9
strand                  +               +
length              31318           43064
in_matrix            True            True
mean             0.137594         0.25672
std              0.380048        0.520162
cv               2.762105        2.026184
fano             1.049733        1.053944

## Update and Write H5AD Ground Truth

In [20]:
output_h5ad_name = '/data2/czbenchmarks/replogle_k562_essential_perturbpredict_de_results_control_cells_v2.h5ad'

print('Adding control cell ids')
adata.uns['control_cells_ids'] = control_cells_ids

print('Adding de results wilcoxon')
adata.uns['de_results_wilcoxon'] = de_results['wilcoxon']#.to_json(double_precision=15)

# print('Adding de results t_test')
# adata.uns['de_results_t_test'] = de_results['t_test'].to_json(double_precision=15)

print('Saving h5ad file')
sc.write(output_h5ad_name, adata)
print('Finished')

Adding control cell ids
Adding de results wilcoxon
Saving h5ad file
Finished

In [21]:
! md5sum {output_h5ad_name}

24db3b89184af1994ba36a1e08db95fb  /data2/czbenchmarks/replogle_k562_essential_perturbpredict_de_results_control_cells.h5ad

In [26]:
print('Copying to cache')
output_file_basename = os.path.basename(output_h5ad_name)
! cp {output_h5ad_name} /home/mgill/.cz-benchmarks/datasets/{output_file_basename}

print('Finished')

Copying to cache
Finished

In [27]:
print('Copying to s3')
output_file_basename = os.path.basename(output_h5ad_name)
! rclone copy {output_h5ad_name}  swift-bio-foundation-s3:/scgym-files/{output_file_basename} --verbose
print('Finished')

Copying to s3
2025/09/25 11:41:02 NOTICE: s3: s3 provider "" not known - please set correctly
2025/09/25 11:42:02 INFO  :
Transferred:   	      710 MiB / 3.043 GiB, 23%, 11.660 MiB/s, ETA 3m26s
Transferred:            0 / 1, 0%
Elapsed time:        59.7s
Transferring:
 * replogle_k562_essentia…_control_cells_v2.h5ad: 22% /3.043Gi, 11.904Mi/s, 3m22s

2025/09/25 11:43:02 INFO  :
Transferred:   	    1.475 GiB / 3.043 GiB, 48%, 12.919 MiB/s, ETA 2m4s
Transferred:            0 / 1, 0%
Elapsed time:      1m59.7s
Transferring:
 * replogle_k562_essentia…_control_cells_v2.h5ad: 48% /3.043Gi, 13.039Mi/s, 2m3s

2025/09/25 11:44:02 INFO  :
Transferred:   	    2.251 GiB / 3.043 GiB, 74%, 12.900 MiB/s, ETA 1m2s
Transferred:            0 / 1, 0%
Elapsed time:      2m59.7s
Transferring:
 * replogle_k562_essentia…_control_cells_v2.h5ad: 73% /3.043Gi, 12.980Mi/s, 1m2s

2025/09/25 11:45:02 INFO  :
Transferred:   	    3.043 GiB / 3.043 GiB, 100%, 10.638 MiB/s, ETA 0s
Transferred:            0 / 1, 0%
Elapsed time:      3m59.7s
Transferring:
 * replogle_k562_essentia…_control_cells_v2.h5ad:100% /3.043Gi, 10.753Mi/s, 0s

2025/09/25 11:45:07 INFO  : replogle_k562_essential_perturbpredict_de_results_control_cells_v2.h5ad: Multi-thread Copied (new)
2025/09/25 11:45:07 INFO  :
Transferred:   	    3.043 GiB / 3.043 GiB, 100%, 7.704 MiB/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:       4m4.6s

Finished

In [24]:
adata.shape, len(adata.uns['control_cells_ids'].keys()), adata.uns['de_results_wilcoxon'].shape

((310385, 8563), 2057, (20793007, 7))

In [15]:
adata.shape, len(adata.uns['control_cells_ids'].keys()), adata.uns['de_results_wilcoxon'].shape, adata.uns['de_results_t_test'].shape

((310385, 8563), 2058, (20793007, 7), (16334637, 9))